import fs from "node:fs";

import { call, run } from "effection";
import type { Operation } from "effection";
import { describe, expect, test } from "vitest";

import type { Fixture } from "../tests/support/fixture.js";
import { plain, rule, useFixture } from "../tests/support/fixture.js";
import type { Rule } from "./generated/gazelle/v1/language_pb.js";
import type { Trace } from "./trace.js";
import { trace } from "./trace.js";
import { discoverProjects, projectOutputs } from "./tsconfig.js";
import { discoverProviders } from "./vite.js";

// Traces entries of a fixture package, as a project when `config` names one.
function* traced(
  fixture: Fixture,
  rel: string,
  options: {
    entries?: string[];
    config?: string;
    rules?: Rule[];
    excluded?: string[];
    observe?: (phase: string) => void;
  },
): Operation<Trace> {
  options.observe?.("building package inventory");
  const pkg = fixture.pkg(rel, options.rules, options.excluded);
  options.observe?.("discovering projects");
  const projects = discoverProjects(pkg, []);
  options.observe?.("building trace scope");
  const project = projects.find((item) => item.local === options.config);
  const scope = {
    pkg,
    emissions: new Map(projects.flatMap((item) => [...projectOutputs(item, pkg)])),
    providers: new Map([
      ...projects.map((item) => [item.file, item.name] as const),
      ...discoverProviders(pkg).map((item) => [item.file, item.name] as const),
    ]),
  };
  const entries =
    options.entries ?? project!.parsed.fileNames.map((file) => pkg.workspace.relative(file));
  options.observe?.("tracing entries");
  const result = yield* call(() =>
    trace(
      scope,
      entries,
      project && {
        name: project.name,
        file: project.file,
        options: project.parsed.options,
        compilations: project.compilations,
        kit: project.extended.some((file) => file.endsWith("/node_modules/$app/tsconfig.json")),
      },
    ),
  );
  options.observe?.("trace completed");
  return result;
}

describe("projects", () => {
  test("erased type imports and automatic types are dependencies", (context) =>
    run(function* () {
      const started = performance.now();
      const phases: { phase: string; milliseconds: number }[] = [];
      const observe = (phase: string) => {
        phases.push({ phase, milliseconds: performance.now() - started });
      };
      context.onTestFailed(() => {
        console.error("Dependency tracing timings:", phases);
      });
      const fixture = yield* useFixture({}, observe);
      const result = yield* traced(fixture, "lib", { config: "tsconfig.test.json", observe });
      expect(result.problems).toEqual([]);
      expect(plain(result.deps.value("lib"))).toEqual([
        "@pnpm//node_modules/@types/node",
        "@pnpm//node_modules/vitest",
      ]);
      // The manifest nft reads for the module format; rules leave it out.
      expect([...result.files].toSorted()).toEqual([
        "lib/package.json",
        "lib/src/index.ts",
        "lib/src/value.test.ts",
        "lib/src/value.ts",
        "lib/vitest.config.ts",
      ]);
    }));

  test("Svelte scripts, SvelteKit modules, paths and other packages resolve", () =>
    run(function* () {
      const fixture = yield* useFixture();
      const result = yield* traced(fixture, "app", { config: "tsconfig.json" });
      expect(result.problems).toEqual([]);
      expect(plain(result.deps.value("app"))).toEqual([
        "//lib",
        "@pnpm//node_modules/@sveltejs/adapter-static",
        "@pnpm//node_modules/@sveltejs/kit",
        "@pnpm//node_modules/@types/node",
        "@pnpm//node_modules/vite",
        "@pnpm//node_modules/vitest",
        { reference: "file:app/generated/api.ts", fallback: "//app/generated:api.ts" },
      ]);
      expect(result.files).toContain("app/src/lib/widget.svelte");
    }));

  test("SvelteKit's generated files are inherited through the generated configuration, never traced", () =>
    run(function* () {
      const fixture = yield* useFixture({
        "app/src/lib/env.ts":
          'import type {} from "../../node_modules/$app/types/index";\n\nexport {};\n',
        "app/tsconfig.plain.json": JSON.stringify({
          extends: "../tsconfig.base.json",
          include: ["src/lib/env.ts"],
        }),
      });
      const inheriting = yield* traced(fixture, "app", { config: "tsconfig.json" });
      expect(inheriting.problems).toEqual([]);
      expect([...inheriting.files].filter((file) => file.includes("node_modules/$app"))).toEqual(
        [],
      );
      const other = yield* traced(fixture, "app", { config: "tsconfig.plain.json" });
      expect(other.problems).toEqual([
        "app/src/lib/env.ts: app/node_modules/$app/types/index.d.ts is generated by SvelteKit; extend app/node_modules/$app/tsconfig.json in app/tsconfig.plain.json to inherit it",
      ]);
    }));

  test("computed imports are problems", () =>
    run(function* () {
      const fixture = yield* useFixture({
        "app/src/lib/dynamic.ts": [
          "export const load = (name: string) => import(name);",
          'export const local = () => import("./format.js");',
          "export const file = (name: string) => import.meta.resolve(`./${name}`);",
        ].join("\n"),
      });
      const result = yield* traced(fixture, "app", { config: "tsconfig.json" });
      expect(result.problems).toEqual([
        "app/src/lib/dynamic.ts: computed import() needs its dependencies declared and kept",
        "app/src/lib/dynamic.ts: computed import.meta.resolve() needs its dependencies declared and kept",
      ]);
    }));

  test("a self import resolves to the project's own sources", () =>
    run(function* () {
      const fixture = yield* useFixture({
        "lib/src/self.ts":
          'import type { value } from "@fixture/lib";\nexport type Value = typeof value;\n',
      });
      const result = yield* traced(fixture, "lib", { config: "tsconfig.lib.json" });
      expect(result.problems).toEqual([]);
      expect(plain(result.deps.value("lib"))).toEqual(["@pnpm//node_modules/@types/node"]);
      expect(result.files).toContain("lib/src/index.ts");
    }));

  test("another project's outputs resolve to the package's js_package", () =>
    run(function* () {
      const fixture = yield* useFixture({
        "lib/src/self.ts":
          'import type { value } from "@fixture/lib";\nexport type Value = typeof value;\n',
      });
      const publication = rule("js_package", "lib", { srcs: [":lib_tsc"] });
      const result = yield* traced(fixture, "lib", {
        config: "tsconfig.test.json",
        rules: [publication],
      });
      expect(result.problems).toEqual([]);
      expect(plain(result.deps.value("lib"))).toContain(":lib");

      const unpublished = yield* traced(fixture, "lib", { config: "tsconfig.test.json" });
      expect(unpublished.problems).toEqual([
        "lib/src/self.ts: lib/dist/index.d.ts is a TypeScript output; declare the package's js_package target so imports resolve to it",
      ]);

      const cycle = rule("js_package", "lib", { srcs: [":test_tsc"] });
      const cyclic = yield* traced(fixture, "lib", {
        config: "tsconfig.test.json",
        rules: [cycle],
      });
      expect(cyclic.problems).toEqual([
        "lib/src/self.ts: imports lib/dist/index.d.ts, which lib publishes from test_tsc; map the import to source in lib/tsconfig.test.json",
      ]);
    }));
});

describe("runtime", () => {
  test("configuration imports are traced without erased types", () =>
    run(function* () {
      const fixture = yield* useFixture();
      const result = yield* traced(fixture, "app", { entries: ["app/vitest.config.ts"] });
      expect(result.problems).toEqual([]);
      expect(plain(result.deps.value("app"))).toEqual([
        ":vite_config",
        "@pnpm//node_modules/vitest",
      ]);
    }));

  test("import.meta.resolve literals are dependencies", () =>
    run(function* () {
      const fixture = yield* useFixture();
      const result = yield* traced(fixture, "app", { entries: ["app/.storybook/main.ts"] });
      expect(result.problems).toEqual([]);
      expect(plain(result.deps.value("app"))).toEqual([
        ":storybook_vite_config",
        "@pnpm//node_modules/@storybook/svelte-vite",
      ]);
    }));

  test("platform-specific packages are selected and renamed members aliased", () =>
    run(function* () {
      const fixture = yield* useFixture({
        "app/src/platform.ts": 'import "fsevents";\nimport "renamed";\n',
      });
      const index = JSON.parse(fs.readFileSync(fixture.index, "utf8"));
      index.packages.app.bindings.renamed = { ...index.packages.app.bindings["@fixture/lib"] };
      fs.writeFileSync(fixture.index, JSON.stringify(index));
      const result = yield* traced(fixture, "app", { entries: ["app/src/platform.ts"] });
      expect(plain(result.deps.value("app"))).toEqual({
        concatenation: [
          ["//lib"],
          {
            select: {
              "//gazelle/platforms:darwin_arm64": ["@pnpm//node_modules/fsevents"],
              "//conditions:default": [],
            },
          },
        ],
      });
      expect(result.aliases).toEqual(new Map([["renamed", "//lib"]]));
    }));

  test("excluded and unbound imports are problems", () =>
    run(function* () {
      const fixture = yield* useFixture({
        "app/src/excluded/value.ts": "export const value = 1;",
        "app/src/imports.ts": 'import "./excluded/value.js";\nimport "unbound";\n',
      });
      const result = yield* traced(fixture, "app", {
        entries: ["app/src/imports.ts"],
        excluded: ["src/excluded"],
      });
      expect(result.problems).toEqual([
        "app/src/imports.ts: app/src/excluded/value.ts is excluded by Gazelle; stop excluding it or keep the attribute",
        "app/src/imports.ts: unbound has no pnpm binding in //app",
      ]);
    }));
});
