load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

package(default_visibility = ["//visibility:private"])
# Starlark library dependency graph.

bzl_library(
    name = "defs",
    srcs = ["defs.bzl"],
    visibility = ["//visibility:public"],
    deps = ["@io_bazel_rules_go//go:def"],
)

exports_files(
    ["defs.bzl"],
    visibility = ["//visibility:public"],
)
